const data = [
    {
        name: 'Transitional Interior Design',
        description: 'Let’s start with one of the most popular styles in the design world today. Transitional design is what we like to call the happy medium of interior design styles. This is the style for you if traditional design is too stuffy, but contemporary is too out of your comfort zone. Transitional is the perfect mix of traditional elegance with contemporary lines and textiles. In addition, transitional interiors keep accessories to a minimum. It’s important to let the furniture and the textiles do the talking. Take advantage of area rugs, throw pillows, and blankets to accessorize.Perhaps the most aesthetically pleasing aspect of the transitional design style is the mix of masculine and feminine. Curved furniture and finishes like wood, rattan, steel, and lacquer are common elements. Furthermore, the combination of two very different styles creates an interesting and welcoming home design perfect for entryways and other rooms. We’re getting so many entryway design ideas from this mixture of dark wood and mirrored furniture.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/transitional-interior-design-styles.jpg',
        price: 2400
    },
    {
        name: 'Traditional Interior Design',
        description: 'When it comes to defining different interior design types one of the most well-known styles is traditional interior design. Traditional interiors use tables and chairs made from dark wood that is ornately detailed. Traditional design draws its inspiration from 18th & 19th Century England and France. This explains why it’s common to find expensive textiles like silk, velvet, and linen used everywhere from upholstery to window treatments. Fabrics also feature a variety of different patterns. A few popular patterns include; damask, florals, stripes, and plaids, for example. Furthermore, traditional homes also like to bring in a sense of glam with crystal chandeliers. European décor heavily influences traditional interiors. Most traditional homes have a very neutral color palette with pops of color brought in with oil paintings or floral arrangements. If you’re not into ‘matchy-matchy’ traditional may not be your cup of tea. Above all, consistency is key so it’s common to find matching furniture sets.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/tradtional-style-bedroom-design.jpg',
        price: 3000
    },
    {
        name: 'Modern Interior Design',
        description: 'We’re here to clear up the difference between modern and contemporary. In spite of their number of similarities, there are a few big signs that you’re looking at a modern interior. Modern design refers to a specific time period while contemporary design is ever-evolving. Modern interior design came on the radar in the early to mid 20th century. Due to the mix of Scandinavian, mid-century modern, and post-modern design, we have our current definition of modern. For example, furniture has clean lines with smooth, sleek surfaces. In particular metal, chrome, and glass are favorite choices among designers. However, with modern interiors, décor is kept minimal. They tend to ditch the knick-knacks and use art as the main décor. It’s common to see bold colorful accents in art and furniture in a mostly neutral space.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/modern-interior-design-styles.jpg',
        price: 5000
    },
    {
        name: 'Eclectic Interior Design',
        description: 'There are common misunderstandings when it comes to the eclectic design style. A few different key features identify eclectic interior design. Think of it as a high-energy collection of carefully selected pieces brought together to create a culture rich interior. Because of this, many think eclectic design has an anything-goes spirit. However, there is a fine line between layered and collected, and busy and distracting. Stick to a neutral color palette and use a select few accent colors to bring in the worldly vibe you’re looking for. With this in mind, the ideal eclectic interior balances color and texture. As a result, it’s the perfect blend of old and new.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/eclectic-bedroom-interior-design.jpg',
        price: 2500
    },
    {
        name: 'Contemporary Interior Design',
        description: 'When you look at interior design styles throughout history contemporary interior design is the one style that is always evolving. The contemporary design style will most likely continue to change over the course of the twenty-first century. Contemporary refers to anything of the present moment. This unique interior design style borrows from various time periods which creates an environment fit to last a lifetime. Contemporary interior design is a sleek and simple space. It uses different features like detailed moldings on walls and windows and open layouts to create an interesting and distinct space. Typical contemporary furniture shows exposed legs and clean lines to give a light and airy feel. It’s common to see materials like metal and glass used because of their light-reflecting properties. This look is the ultimate mix of house décor styles. In addition, neutral color palettes are the most common for contemporary design with textured fabrics to create interest. Thus, creating the perfect luxury modern interior.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/contemporary-style-interior-design.jpg',
        price: 7500
    },
    {
        name: 'Minimalist Interior Design',
        description: 'Contemporary design and minimalist design have a lot of the same qualities. Both have uncomplicated forms, clean lines, and simple finishes. However, the minimalist decorating style is inspired by Japanese design and concentrates on the principle that less is more. In the end, minimalist design loves empty space. While most minimalist interiors have a neutral color scheme, primary colors can also be used as an accent color. Patterns are nowhere to be found and texture is a necessity. Because of the less is more philosophy you’ll find functional furniture is the most essential design element. Storage is also important in minimalist interior design. For this reason, furniture often doubles as hidden storage. For example, a coffee table that lifts up to reveal storage is one of the many creative solutions minimal interiors use.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/minimalist-interior-design-styles.jpg',
        price: 5500
    },
    {
        name: 'Bohemian Interior Design',
        description: "Similarly to the mid-century style, bohemian interiors are continuing to gain popularity. Because so many retailers are jumping on the boho train there is no better time than now to explore your bohemian side. In a nutshell, bohemian design is a free-spirited aesthetic that mixes different cultures and artistic expressions into an eclectic style that thinks outside the box. A laid back boho atmosphere places an emphasis on nature. However, it’s common to find bold patterns and bright colors for furniture and accents. When you walk into a home that has a bohemian design style you immediately feel immersed in another culture. Trinkets are displayed from travels and the whole vibe feels very nomadic. When we compare different design styles Bohemian is one of the few where order isn’t necessary. Mixing patterns and colors is encouraged. Likewise, we’re also seeing a trend of modern boho style. The addition of animal hides, metallic accents, and rich wood help modernize this collected style. We love that Bohemian style interiors use things in unconventional ways. Try this fresh living room idea for an example: try hanging a vintage rug on the wall for a fresh unique take on artwork.",
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/bohemian-style-living-room-design.jpg',
        price: 8500
    },
    {
        name: 'Modern Farmhouse Interior Design',
        description: 'Our list of house décor styles wouldn’t be complete without modern farmhouse interior design. Joanna Gaines has earned the title as farmhouse queen, but even she is blending her farmhouse style into a more modern, and collected space. Modern farmhouse interiors have many characteristics of what we know as traditional farmhouse design. On the other hand, things become more simplified and clean without losing their character. Shiplap isn’t going anywhere and we still want to see barn doors galore. Modern updates like wide plank floors, open concept living, and sleek lighting are a few common identifiers of the modern farmhouse decorating style. Farmhouse interiors are also known for mixing metals. From gold to black to nickel, contrast is your friend. In addition, we love that this unique design style takes its connection to nature seriously. It’s essential to have raw wood elements and greenery that can be found in every room. Consequently, color palettes in modern farmhouse interiors are always on the neutral side. When you want to add that extra pop of color it’s important to pull from nature. For example, try adding deep navy, sage green, or burnt orange.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/modern-farmhouse-interior-design-style-living-room.jpg',
        price: 3500
    },
    {
        name: 'Coastal Interior Design',
        description: 'You don’t have to live by the beach to appreciate the coastal interior design style. Not to be confused with nautical décor, the coastal decorating style is in another league of its own. A coastal space makes note of its natural environment. This can be seen through the color palette down to the materials used for furniture and accessories. Neutrals like whites are paired with beige to mimic the sand. Additionally, pops of blues to resemble the surf and sunny summer skies. Furthermore, coastal style homes should always feel bright and breezy. The intention is to feel like there is nothing between the indoors and outdoors. Because of this window treatments are kept to a minimum. A light sheer fabric blowing in the wind is sure to get the coastal vibe across. You won’t find anchors and seashells scattered everywhere for this interior design style. Instead, you’ll find blue glass vases, striped wallpaper, or abstract paintings that get the coastal feeling across. When it comes to identifying furniture in coastal interiors they have a very comfortable lived in feel. Painted and distressed furniture paired with wicker or jute makes for a match made in heaven. Because connecting to nature is so important with the coastal interior design style the addition of indoor plants is a must-have.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/coastal-interior-design-styles.jpg',
        price: 6600
    },
    {
        name: 'Southwestern Interior Design',
        description: 'The southwestern style as we know it today is not the same as it was when it first became noticeable in the design world. And it will continue evolving as the years pass by. Southwestern interiors gather their inspiration from the soft lines of adobe houses, Spanish textiles, ironwork and nature. Color pallets have various colors found in the American desert. Rust, terracotta, and cactus green, are a few favorites amongst designers. Whereas furniture is more on the heavy side, often adorning thick legs and bulky finishes. Additionally, texture is southwestern interior designs best friend. Leather and suede are the most common upholstery material.',
        img: 'https://cdn-bnokp.nitrocdn.com/QNoeDwCprhACHQcnEmHgXDhDpbEOlRHH/assets/static/optimized/rev-86e5434/online-decorating/wp-content/uploads/2019/06/southwestern-style-home.jpg',
        price: 6700
    },
]